### ISSUE TITLE
2.58b can be refined

### ISSUE THREAD

**Issue by sillykelvin** [felix021/sicp#1]
你看这么快，现在轮到我来找你对答案了。。 :-D

2.58b的答案，其实还可以再优化，例如：

```
(deriv '(x + 2 * x * y) 'x) => (1 + (2 * y))
```

其实按原题目的要求，优化成`(1 + 2 * y)`是最好的~~ :-D

本来在gtalk上讲一下就可以了，不过我是用手机上的gtalk，打字不方便，所以就到这里提个issue好了。。 :-P

**Comment by felix021** [comment]
嗯，这种优化可以做，而且还可以做得更多（比如说 (1 \* x + 2 \* x) 还可以再合并成 3 \* x）；书上102页也说了代数化简是一个非常复杂的问题，“还有另一个根本性的问题：对于某种用途的最简形式，对于另一用途可能不是最简形式”。所以我觉得进一步的结果化简不是很有必要，主要还是解决输入格式的问题 :-)
